#!/bin/bash

help_text="$(cat<<-EOF
My Personal Script to help me create my initial setup for HTB Machines\n
Options:\n
-h|--help   Prints this help text and exits\n
-b|--box    To specify name of the machine you are going to attempt\n
-f|--fort   To specify name of the fortress you are going to attempt\n
\n
Usage:\n
htb -b <box-name>\n
htb -f <fort-name>\n
OR\n
htb --box <box-name>\n
htb --fortress <fort-name>\n

EOF
)" 

if [[ $# -eq 0 ]] ; then
  echo -e $help_text
  exit 0
fi

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      echo -e $help_text
      exit 0
      ;;
    -b|--box)
      shift
      if test $# -gt 0; then
        export BOX=$1
      else
        echo "Please Specify a box name!"
        echo "htb -h for more info"
        exit 1
      fi
      shift
      ;;
    -f|--fortress)
      shift
      if test $# -gt 0; then
        export FORT=$1
      else
        echo "Please Specify a fort name!"
        echo "htb -h for more info"
        exit 1
      fi
      shift
      ;;
      *)
      echo $help_text
      break
      ;;
  esac
done

if [ ! -z ${BOX+x} ] ; then
  cd /root/htb/boxes/
  if [ -d "/root/htb/boxes/$BOX" ] ; then
    cd $BOX
  else
    mkdir $BOX
    cd $BOX
    mkdir nmap
    sudo -u pachinko touch /home/pachinko/Desktop/htb/boxes/$BOX.ctd
  fi
  sudo -u pachinko cherrytree /home/pachinko/Desktop/htb/boxes/$BOX.ctd &> /dev/null &
  tmux -u -2 new -s $BOX

elif [ ! -z ${FORT+x} ] ; then
  cd /root/htb/forts/
  if [ -d "/root/htb/forts/$FORT" ] ; then
    cd $FORT
  else
    mkdir $FORT
    cd $FORT
    mkdir nmap
    sudo -u pachinko touch /home/pachinko/Desktop/htb/forts/$FORT.ctd
  fi
  sudo -u pachinko cherrytree /home/pachinko/Desktop/htb/forts/$FORT.ctd &>/dev/null &
  tmux -u -2 new -s $FORT
fi
